[package]
name = "flight_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "53.2.0"
tokio = "1.41.0"
tonic = "0.12.3"
futures = "0.3.31"
arrow-flight = "53.2.0"